### ISSUE TITLE
ubuntu 22.04 fatal error

### ISSUE THREAD

**Issue by Interfud** [jrbrtsn/ban2fail#4]
root@alex-VirtualBox:/home/alex/ban2fail-0.14.3# make release
cntry.c:20:10: fatal error: GeoIP.h: No such file or directory
   20 | #include <GeoIP.h>
      |          ^~~~~~~~~
compilation terminated.
cc -c  -g0 -O3 -Wreturn-type -Wformat -Wchar-subscripts -Wparentheses -Wcast-qual -Wmissing-declarations   -DNDEBUG -std=gnu99 cntry.c -o release/cntry.o
cntry.c:20:10: fatal error: GeoIP.h: No such file or directory
   20 | #include <GeoIP.h>
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:249: release/cntry.o] Error 1
make: *** [Makefile:87: release] Error 2
root@alex-VirtualBox:/home/alex/ban2fail-0.14.3# ls
add-addrs.sh  ban2fail.cfg      cfgmap.h     dynstack.h   ez_libanl.h  ez_libpthread.c  install.sh  logFile.c  map.c       msgqueue.h  pdns.c     release   timestamp.c
addrRpt.c     ban2fail.h        cntry.c      es.c         ez_libc.c    ez_libpthread.h  iptables.c  logFile.h  map.h       obsvTpl.c   pdns.h     str.c     timestamp.h
addrRpt.h     ban2fail.service  cntry.h      es.h         ez_libc.h    ez_libz.c        iptables.h  logType.c  maxoff.c    obsvTpl.h   ptrvec.c   str.h     TODO.txt
b2f-grep.c    ban2fail.sh       cron-rpt.sh  ez.h         ez_libdb.c   ez_libz.h        Jmakefile   logType.h  maxoff.h    offEntry.c  ptrvec.h   target.c  util.c
ban2fail.c    cfgmap.c          dynstack.c   ez_libanl.c  ez_libdb.h   fsckdns.c        LICENSE     Makefile   msgqueue.c  offEntry.h  README.md  target.h  util.h

**Comment by jrbrtsn** [comment]
jdr@jdr-laptop:~$ **apt-file search GeoIP.h**
i2p-doc: /usr/share/i2p/docs/javadoc/net/i2p/router/transport/GeoIP.html
i2p-doc: /usr/share/i2p/docs/javadoc/net/i2p/router/transport/class-use/GeoIP.html
**libgeoip-dev: /usr/include/GeoIP.h**  <-- **Install `libgeoip-dev' package**
pike8.0-doc: /usr/share/doc/pike8.0-doc/html/reference/ex/predef_3A_3A/Geography/GeoIP.html
wireshark-doc: /usr/share/doc/wireshark-doc/wsdg_html_chunked/ChLibsGeoIP.html

**Comment by Interfud** [comment]
Thanks. Everything works on ubuntu 22.04
